name: Docker CI 's
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
        
        - name: Build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog-service main.go

        - name: unit tests
          run: |
            cd src/product-catalog
            go test ./...
    
    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Install Docker
          uses: docker/setup-buildx-action@v3
        
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Docker product-catalog Push
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: src/product-catalog/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}
          
        - name: Docker accounting Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/accounting/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/accounting:${{github.run_id}}

        - name: Docker ad  Push
          uses: docker/build-push-action@v6
          with:
            context: src/ad
            file: src/ad/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/ad:${{github.run_id}}

        - name: Docker cart  Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/cart/src/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/cart:${{github.run_id}} 

        - name: Docker checkout Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/checkout/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/checkout:${{github.run_id}} 

        - name: Docker email Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/email/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/email:${{github.run_id}}

        - name: Docker flagd-ui Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/flagd-ui/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/flagd-ui:${{github.run_id}}

        - name: Docker fraud-detection Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/fraud-detection/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/fraud-detection:${{github.run_id}}

        - name: Docker frontend Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/frontend/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{github.run_id}}

        - name: Docker frontend-proxy Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/frontend-proxy/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{github.run_id}}

        - name: Docker image-provider Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/image-provider/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/image-provider:${{github.run_id}}

        - name: Docker load-generator Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/load-generator/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/load-generator:${{github.run_id}}

        - name: Docker payment Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/payment/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/payment:${{github.run_id}}

        - name: Docker quote Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/quote/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/quote:${{github.run_id}}

        - name: Docker shipping Push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: src/shipping/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/shipping:${{github.run_id}}

        - name: Docker recommendation Push
          uses: docker/build-push-action@v6
          with:
            context: src/recommendation
            file: src/recommendation/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/recommendation:${{github.run_id}}

    updatek8s:
            runs-on: ubuntu-latest

            needs: docker

            steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.TOKEN }}

            - name: Update tag in kubernetes deployment manifest
              run: | 
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}|" kubernetes/productcatalog/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/accounting:${{github.run_id}}|" kubernetes/accounting/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/ad:${{github.run_id}}|" kubernetes/ad/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/cart:${{github.run_id}}|" kubernetes/cart/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/checkout:${{github.run_id}}|" kubernetes/checkout/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/email:${{github.run_id}}|" kubernetes/email/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flagd-ui:${{github.run_id}}|" kubernetes/flagd-ui/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/fraud-detection:${{github.run_id}}|" kubernetes/fraud-detection/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{github.run_id}}|" kubernetes/frontend/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{github.run_id}}|" kubernetes/frontend-proxy/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/image-provider:${{github.run_id}}|" kubernetes/image-provider/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/load-generator:${{github.run_id}}|" kubernetes/load-generator/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/payment:${{github.run_id}}|" kubernetes/payment/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/quote:${{github.run_id}}|" kubernetes/quote/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/shipping:${{github.run_id}}|" kubernetes/shipping/deploy.yaml
                  sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/recommendation:${{github.run_id}}|" kubernetes/recommendation/deploy.yaml

            
            - name: Commit and push changes
              run: |
                git config --global user.email "veeraganesh6@gmail.com"
                git config --global user.name "veera ganesh"
                git add kubernetes/*
                git commit -m "[CI]: Update images tag"
                git push origin HEAD:main -f